name: Arduino Build

on:
  push:
    paths:
      - '**.ino'
  pull_request:
    paths:
      - '**.ino'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install Platform Support
        run: |
          arduino-cli core update-index
          # Ganti esp32:esp32 jika Anda menggunakan board lain (misal arduino:avr)
          arduino-cli core install esp32:esp32 

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:devkitv1 ./serialread.ino
